---
title: "Course support"
---

## Lectures

If you ever have a question during lecture please ask it. If you're confused then it's a guarantee someone else is. Plus, interacting with the instructor is what you're paying to do!

## Office hours

Office hours are here for your support— take advantage of that. Most of the time the questions we have *can* be tackled independently, but it's usually a 5 minute fix in office hours. I can't help you learn if I don't know what you're struggling with.

## Email

Try to refrain from emailing about course content if it isn't pressing. If possible, try to bring your questions to office hours or ask me after class. 

If you need to communicate concerns or schedule an appointment with me outside of class time then feel free to email me at rmsholl@ksu.edu; I try to respond to emails within 2 business days maximum.

## Stat Help Lab

The Department of Statistics runs a free tutoring lab between the hours of 9 AM and 5 PM, Monday through Friday, all semester after the second week of class. All of the help lab workers are graduate students and instructors in the department so your question will rarely be outside of their capabilities. The lab runs on a "firt come, first serve" basis— if there's no one available when you're trying to get help you can always come back at a different time. 

### Mental Health

Your mental health and good relationships are vital to your overall well-being. Symptoms of mental health issues may include excessive sadness or worry, thoughts of death or self-harm, inability to concentrate, lack of motivation, or substance abuse. Although problems can occur anytime for anyone, you should pay extra attention to your mental health if you are feeling academic or financial stress, discrimination, or have experienced a traumatic event, such as loss of a friend or family member, sexual assault or other physical or emotional abuse.
If you are struggling with these issues, do not wait to seek assistance.

- [Kansas State University Counseling Services](https://www.k-state.edu/counseling/) offers free and confidential services to assist you to meet these challenges. 

- [Lafene Health Center](https://www.k-state.edu/lafene) has specialized nurse practitioners to assist with mental health. 

- [Office of Student Life](https://www.k-state.edu/studentlife/) can direct you to additional resources. 

- [K-State Family Center](https://www.hhs.k-state.edu/familycenter/) offers individual, couple, and family counseling services on a sliding fee scale.

- [Center for Advocacy, Response, and Education](https://www.k-state.edu/care/) (CARE) provides free and confidential assistance for those in our K-State community who have been victimized by violence.

- K-State Online students have free access to mental health counseling with [TELUS Help Student Support](https://www.k-state.edu/lafene/well-being/telushealth/) - 24/7 support via chat and phone.

- The [Division of Academic Success and Student Affairs](https://www.k-state.edu/academic-success-student-affairs/) can direct you to additional resources.
